//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adswerve_Books
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string book_id { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
